### ISSUE TITLE
Character argument

### ISSUE THREAD

**Issue by hkjels** [component/trim#5]
Would it not make sense to have the ability to choose what type of character to trim? Of course defaulting to whitespace.

**Comment by Trott** [comment]
More than six years later.... Given that https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim is now an API in JavaScript, I'd say it's best to be consistent with that API. This is basically a polyfill/alias for it wherever possible. That API does not take any argument, so I'd be inclined to think that `trim()` should not take an argument either.
